### ISSUE TITLE
Preact Support

### ISSUE THREAD

**Issue by anantoghosh** [gigobyte/ui-stack#2]
[Preact](https://preactjs.com/) support can be added.

https://www.bountysource.com/issues/43783194-preact-support
Detection code has been given by the author of Preact.

Quote from link:
```js
function isPreact() {
  var all = document.querySelectorAll('*');
  for (let i=all.length; i--; ) {
    if (typeof Symbol!=='undefined' && all[i][Symbol.for('preactattr')] || all[i].__preactattr_) {
      return true;
    }
  }
  return false;
}
```
You can test it out on preactjs.com or webpack.js.org.

Alternatively, here's one that checks for _component - technically this would produce a false negative for sites built without components, but that should be few/no sites:
```js
function isPreact() {
  return [].some.call(document.querySelectorAll('*'), node => node._component);
}
```

**Comment by gigobyte** [comment]
Thanks for the snippet! I'll be adding it soon.
